### PR TITLE
rubocop autofixes

### PR DESCRIPTION
**Pull request by ndushay**
@peetucket @cbeer

### CODE REVIEW

**Comment by ndushay** [comment]
I don't understand why hound is complaining here.  .hound.yml is in master  sul-dlss/harvestdor-indexer/blob/master/.hound.yml.  Is it that weirdo rubocop doesn't recognize its own autoconfig cops issue?  Or hound doesn't understand rspec?

Tests are ok except for hound.

**Comment by ndushay** [comment]
ok, put change in .rubocop.yml  per sul-dlss/gdor-indexer#61.   Hound still has 3 violations, but I don't know what they are.

**Comment by ndushay** [comment]
@cbeer @peetucket   this is finally a clean PR.  w00t!

**Comment by cbeer** [comment]
Can these commits be squashed?

**Comment by ndushay** [comment]
@cbeer duly squashed.

**Pull request merged**
